data = {

'Name': ['John', 'Anna', None, 'Linda', 'Sophia'],

'Age': [28, 24, 40, None, 25],

'Salary': [50000, 55000, 60000, 70000, 65000],

'Join Date': ['2015-03-15', '2017-07-01', '2018-01-12', '2016-08-05', '2019-11-19'],

'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance'],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Female']

}


df = pd.DataFrame(data)


1. How to fill missing values in a column with a specific value (e.g., 'Unknown' for Name)?

2. How to fill missing numerical values in a column with the mean of that column?

3. How can rows with missing values be removed from a Pandas DataFrame?

In [17]:
import pandas as pd
data = {

'Name': ['John', 'Anna', None, 'Linda', 'Sophia'],

'Age': [28, 24, 40, None, 25],

'Salary': [50000, 55000, 60000, 70000, 65000],

'Join Date': ['2015-03-15', '2017-07-01', '2018-01-12', '2016-08-05', '2019-11-19'],

'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance'],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Female']

}
df = pd.DataFrame(data)
df

     Name   Age  Salary   Join Date Department  Gender
0    John  28.0   50000  2015-03-15         HR    Male
1    Anna  24.0   55000  2017-07-01    Finance  Female
2    None  40.0   60000  2018-01-12         HR    Male
3   Linda   NaN   70000  2016-08-05         IT  Female
4  Sophia  25.0   65000  2019-11-19    Finance  Female

In [16]:
df["Name"]=df["Name"].fillna("Unknown")
df

      Name   Age  Salary   Join Date Department  Gender
0     John  28.0   50000  2015-03-15         HR    Male
1     Anna  24.0   55000  2017-07-01    Finance  Female
2  Unknown  40.0   60000  2018-01-12         HR    Male
3    Linda   NaN   70000  2016-08-05         IT  Female
4   Sophia  25.0   65000  2019-11-19    Finance  Female

In [18]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

     Name    Age  Salary   Join Date Department  Gender
0    John  28.00   50000  2015-03-15         HR    Male
1    Anna  24.00   55000  2017-07-01    Finance  Female
2    None  40.00   60000  2018-01-12         HR    Male
3   Linda  29.25   70000  2016-08-05         IT  Female
4  Sophia  25.00   65000  2019-11-19    Finance  Female

In [22]:
df = pd.DataFrame(data)
df=df.dropna()
df

     Name   Age  Salary   Join Date Department  Gender
0    John  28.0   50000  2015-03-15         HR    Male
1    Anna  24.0   55000  2017-07-01    Finance  Female
4  Sophia  25.0   65000  2019-11-19    Finance  Female

1. How to convert a column to a specific format (e.g., convert a date column to datetime format)?

2. How to filter the data based on a condition (e.g., age > 25)?

3. How to filter the data based on a specific value (e.g., get all rows where Name is 'Anna')?

4. How to select specific columns in the DataFrame (e.g., Name and Salary columns)?

5. How to select specific rows (e.g., first 3 rows)?

6. How to get the rows by index positions (e.g., using .iloc[])?

7. How to sort the data by a specific column in ascending order (e.g., Age)?

8. How to sort the data by a column in descending order (e.g., Salary)?

9. How to group data by a specific column (e.g., Age) and calculate the average salary for each group?

10. How to aggregate multiple statistics on a column (e.g., calculate mean, max, and min salary by Age)?

11. How to apply a function to modify a column (e.g., increasing the salary by 10%) using apply()?

12. How to add a new column to the DataFrame (e.g., adding a column for Bonus)?

13. How to rename columns in the DataFrame (e.g., renaming Join Date to Joining Date)?

14. How to drop a specific column from the DataFrame (e.g., dropping the Bonus column)?

15. How to add a new categorical column, Job Role, to the DataFrame?

16. How to calculate the average salary for each department?

17. How to determine which department has the most employees?

18. How to find which department has the most female employees?

In [2]:
import pandas as pd

data = {

'Name': ['John', 'Anna', 'Peter', 'Linda', 'Sophia'],

'Age': [28, 24, 40, 33, 25],

'Salary': [50000, 55000, 60000, 70000, 65000],

'Join Date': ['2015-03-15', '2017-07-01', '2018-01-12', '2016-08-05', '2019-11-19'],

'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance'],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Female']

}


df = pd.DataFrame(data)

In [3]:
df

     Name  Age  Salary   Join Date Department  Gender
0    John   28   50000  2015-03-15         HR    Male
1    Anna   24   55000  2017-07-01    Finance  Female
2   Peter   40   60000  2018-01-12         HR    Male
3   Linda   33   70000  2016-08-05         IT  Female
4  Sophia   25   65000  2019-11-19    Finance  Female

In [11]:
df[df['Age']>25]

    Name  Age  Salary   Join Date Department  Gender
0   John   28   50000  2015-03-15         HR    Male
2  Peter   40   60000  2018-01-12         HR    Male
3  Linda   33   70000  2016-08-05         IT  Female

In [15]:
df[df["Name"]=="Anna"]

   Name  Age  Salary   Join Date Department  Gender
1  Anna   24   55000  2017-07-01    Finance  Female

In [16]:
df[["Name","Salary"]]

     Name  Salary
0    John   50000
1    Anna   55000
2   Peter   60000
3   Linda   70000
4  Sophia   65000

In [17]:
df.head(3)

    Name  Age  Salary   Join Date Department  Gender
0   John   28   50000  2015-03-15         HR    Male
1   Anna   24   55000  2017-07-01    Finance  Female
2  Peter   40   60000  2018-01-12         HR    Male

In [19]:
df.iloc[1]

Name                Anna
Age                   24
Salary             55000
Join Date     2017-07-01
Department       Finance
Gender            Female
Name: 1, dtype: object

In [21]:
df["Age"].sort_values(ascending=False)

2    40
3    33
0    28
4    25
1    24
Name: Age, dtype: int64

In [22]:
df.sort_values(by="Age")

     Name  Age  Salary   Join Date Department  Gender
1    Anna   24   55000  2017-07-01    Finance  Female
4  Sophia   25   65000  2019-11-19    Finance  Female
0    John   28   50000  2015-03-15         HR    Male
3   Linda   33   70000  2016-08-05         IT  Female
2   Peter   40   60000  2018-01-12         HR    Male

In [29]:
df.groupby(by="Age")["Salary"].mean()

Age
24    55000.0
25    65000.0
28    50000.0
33    70000.0
40    60000.0
Name: Salary, dtype: float64

In [30]:
df.groupby(by="Age")["Salary"].agg(["mean","min","max"])

        mean    min    max
Age
24   55000.0  55000  55000
25   65000.0  65000  65000
28   50000.0  50000  50000
33   70000.0  70000  70000
40   60000.0  60000  60000